### ISSUE TITLE
App's  UI Interaction  not working  after submitting a Bug

### ISSUE THREAD

**Issue by rahul-apple** [Buglife/Buglife-iOS#11]
After submitting a bug its showing  the Bug submitted alert .after that the App  gone freezed state.
no UI Interaction .dont Know the Actual Reason  for that wish to get a Reply ASAP.

**Comment by schukin** [comment]
Hi Rahul - Hmm, that's odd... Once the "bug report" alert has been dismissed, no other code is run on the main thread, thus there shouldn't be any main thread lockup caused by Buglife. I'd like to ask some questions...
1. Is this issue easily reproducible?
2. If it is reproducible, could you attach a sample project that shows the issue?
3. If it is not reproducible, how many times have you witnessed the issue?
4. Is your app swizzling any Foundation / UIKit / networking methods? 
5. Are you using Crashlytics or any 3rd-party crash reporting tools? If so, it might be useful to check to see if you received a crash corresponding with this issue.
6. Can you point to the bug report in your web dashboard corresponding to the instance for which this issue occurred? (You can email me the bug report URL: dave@buglife.com)

Thanks,
Dave

**Comment by schukin** [comment]
After following up with Rahul, this appears to have been caused by another 3rd-party library he was using in his app.
