### ISSUE TITLE
Localizable Strings.

### ISSUE THREAD

**Issue by txaiwieser** [Buglife/Buglife-iOS#18]
Can we have the Strings used in the App in a Localizable.strings? In that way they be easily localizable for any language!

Thanks!

**Comment by schukin** [comment]
Buglife actually doesn't use Localizable.strings, since it is a static library that is embedded into host apps with zero resources; We do this to make it as easy as possible to add or upgrade Buglife in your app :)

If there is a specific language you're looking for, we'd be more than happy to add it for you! (I also noticed you're located in Brazil, and it just so happens we *just* added support for Portuguese in Buglife v1.4.0.)

**Comment by txaiwieser** [comment]
Unfortunately the when the device is in Portuguese Brazil (pt-BR) the localizable are from a language I don't even know. very strange..

**Comment by schukin** [comment]
Whoops! This has been fixed in the latest release (v.1.4.1). Please let us know if you continue to see any issues :)
