### ISSUE TITLE
Setting .invocationOptions = [] still results in prompt when recording video

### ISSUE THREAD

**Issue by okvivi** [Buglife/Buglife-iOS#33]
I am trying to use Buglife with a purely manual invocation.

```
    Buglife.shared().invocationOptions = []
    Buglife.shared().start(withAPIKey: "<my api key>")
```

My app records the screen using ReplayKit's RPScreenRecorder. Whenever a recording is finished, Buglife shows up with a prompt whether I would like to add feedback to the recording.

Any way to disable this prompt?

**Comment by schukin** [comment]
Hi @okvivi -

Buglife does have a [private API for toggling screen recording invocations](https://github.com/Buglife/Buglife-iOS/blob/master/Source/Buglife.m#L96).

Since we won't be able to make this public until our next release in a couple weeks, I can suggest exposing it as a category in your app, then using it in your app delegate. For example:

```
#import <Buglife/Buglife.h>

@interface Buglife (Additions)

@property (nonatomic, getter=isScreenRecordingInvocationEnabled) BOOL screenRecordingInvocationEnabled;

@end
```

Then in your app delegate:

```
[Buglife sharedBuglife].screenRecordingInvocationEnabled = NO;
```

**Comment by okvivi** [comment]
Great, thanks for the reply! Really appreciate it!
