### ISSUE TITLE
Update Docs to explain how to customize floating button

### ISSUE THREAD

**Issue by bbookman** [Buglife/Buglife-iOS#34]
I'd like to understand how to:

- Customize where the button is displayed upon first viewing (I don't like where it starts)
- Customize the icon/image
- Perhaps change it from floating to stationary
- I use an onboarding repo called Instructions which can hook a label onto a UI element .. like 
UIelement.helpLabel.text = "This is the exciting UIelement" ..  How can I do that with the floating button? I'm using Swift and know little about poking around in objc

**Comment by schukin** [comment]
Hi @bbookman - my sincere for the **atrociously** late response here, this one somehow flew under our radar.

The floating bug button API is rather limited; we don't have plans to expand the API at the moment, since the vast majority of users use the screenshot or shake APIs. We do recommend the screenshot API in general, as this tends to be the most intuitive to end-users. That said, we always welcome pull requests :) 

If you're still looking to customize the floating bug button, I can recommend one of three approaches:
A) Fork this repo, and make the necessary changes to [LIFEBugButtonWindow.m](https://github.com/Buglife/Buglife-iOS/blob/3b9bcce9ea5db10a56758ccaddcda80a6cdb40d9/Source/Views/LIFEBugButtonWindow.m)
B) Use method-swizzling to override methods related to presentation of `LIFEBugButtonWindow`
C) Disable the bug button entirely, and create your own bug button by copying code from `LIFEBugButtonWindow`

Please let me know if any of this is unclear. :))

**Comment by bbookman** [comment]
Odd, in my memory you had already responded.  No problem.  Since obj-c is a no go for me, I just decided against the floating bug and went with the other options

**Comment by schukin** [comment]
Ah yes, it may have been via a support email ;) glad it worked out!
