### ISSUE TITLE
Unintended invocations

### ISSUE THREAD

**Issue by onato** [Buglife/Buglife-iOS#40]
I have the invocation options set to `[.shake]`. Some people are reporting that…

> Send feedback keeps popping up for no reason

I have seen once before, that when I returned to the app it was displaying Buglife. I am wondering if the shake event could be happening when people drop their phone down on the table. 

Given my invocation options are only `.shake`, and I am not calling `presentReporter` could there be another explanation for what people are reporting?

**Comment by schukin** [comment]
That's entirely possible; the shake event is generated by iOS, using a system-defined threshold for what constitutes a “shake” (similar to shake-to-undo). 

We actually recommend using the `.screenshot` invocation; this comes much more naturally to users, and also removes the tendency to accidentally trigger the bug reporter. (The only reason `.shake` is the default invocation method is because `.screenshot` can't be triggered in the iOS simulator.)
